exclude: |
  (?x)(
    .*/manifest\.json
  )
repos:
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        language_version: python3.13.4

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-simplify]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii"]

  # TODO: figure out why this takes forever to run in a hook
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.19.1"
  #   hooks:
  #     - id: mypy
  #       pass_filenames: false
  #       additional_dependencies:
  #         - homeassistant==2025.1.0
  #         - voluptuous==0.15.2
  #         - types-setuptools
  #       args:
  #         - --explicit-package-bases
  #         # - ./tests
  #         - ./custom_components
